#!/bin/bash
# Note: Run this as root on a web server

output_dir=/mnt/user_storage/homedirs/help/home/help/helpsite/originalhtml

rm -rf ${output_dir:?'not set'}/*
python /usr/share/MoinMoin/moin-1.9.7/MoinMoin/script/moin.py \
    --config-dir=/home/anywhere/wiki/ \
    --wiki-url=https://www.pythonanywhere.com/wiki/ \
    export dump \
    --target-dir=$output_dir


rm $output_dir/BadContent.html
rm $output_dir/EditorGroup.html
rm $output_dir/StaffGroup.html
rm $output_dir/LanguageSetup.html
rm $output_dir/PythonAnywhere.html
mv $output_dir/PythonAnywhereWiki.html index.html
chown -R help:registered_users $output_dir
